# Generated by Django 4.1.13 on 2025-03-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wins',
            field=models.IntegerField(default=5),
        ),
    ]
